version: "3.9"

services:

  # Create service with Redis
  redis-db:
    image: redis:7-alpine
    container_name: redis-db
    restart: always
    volumes:
      - db-data:/data
    networks:
      - dev-network

  # Create API service
  api:
    container_name: api
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: api.dockerfile
    environment:
      REDIS_SERVER_URL: redis-db:6379
      RESERVATION_TIMEOUT: 5000
    restart: always
    networks:
      - dev-network
    depends_on:
      - redis-db

  # Create Maker service
  maker:
    container_name: maker
    build:
      context: .
      dockerfile: maker.dockerfile
    environment:
      REDIS_SERVER_URL: redis-db:6379
      CONTAINER_BACKEND: swarm
      RESERVATION_TIMEOUT: 5000
      RESERVATION_COOLDOWN: 2000
      RESERVATION_RETRY_TIMES: 3
      CONVERGE_VERIFY_COOLDOWN: 1000
      CONVERGE_VERIFY_RETRY_TIMES: 10
      MAX_CONCURRENT_JOBS: 3
      DOCKER_NETWORK: dev-network
      LOOKUP_COOLDOWN: 1000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dev-network
    depends_on:
      - api
      - redis-db

volumes:
  db-data:

networks:
  dev-network:
    name: dev-network
    external: true