on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
name: Test Go Coverage
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Go setup
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
          cache: true

      - name: Go test
        run: |
          go test -v ./... -covermode=count -coverprofile=coverage.out
          go tool cover -func=coverage.out -o=coverage.out

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: coverage.out