on:
  push:
  workflow_dispatch:
      
name: Test and update coverage
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Checkout wiki
        uses: actions/checkout@v3
        with:
          repository: ${{github.repository}}.wiki
          path: ./.github/wiki/

      - name: Go setup
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
          cache: true

      - name: Go test
        run: go test ./... -count 1 -race -coverprofile coverage.out -covermode atomic

      - name: Calculate coverage
        run: |
          COVERAGE=$(go tool cover -func coverage.out | tail -1 | grep -Eo '[0-9]+\.[0-9]')
          go tool cover -html coverage.out -o coverage.html
          echo "COVERAGE=${COVERAGE}" >> $GITHUB_ENV
          echo "coverage: $COVERAGE% of statements"

      - name: Get attached PR
        uses: jwalton/gh-find-current-pr@v1
        id: finder

      - name: Save PR coverage
        if: steps.finder.outputs.number
        run: |
          mv coverage.html ./.github/wiki/coverage-${{ steps.finder.outputs.number }}.html

      - name: Update coverage comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: steps.finder.outputs.number
        with:
          number: ${{ steps.finder.outputs.pr }}
          recreate: true
          message: |
            Test on ${{ github.sha }} ended successfully.
            Branch tests coverage: [${{ env.COVERAGE }}%](https://raw.githack.com/wiki/st-matskevich/go-matchmaker/coverage-${{ steps.finder.outputs.number }}.html).

      - name: Create main branch coverage badge
        if: github.ref == 'refs/heads/main'
        run: |
          if awk "BEGIN {exit !($COVERAGE >= 90)}"; then
            COLOR=brightgreen
          elif awk "BEGIN {exit !($COVERAGE >= 80)}"; then
            COLOR=green
          elif awk "BEGIN {exit !($COVERAGE >= 70)}"; then
            COLOR=yellowgreen
          elif awk "BEGIN {exit !($COVERAGE >= 60)}"; then
            COLOR=yellow
          elif awk "BEGIN {exit !($COVERAGE >= 50)}"; then
            COLOR=orange
          else
            COLOR=red
          fi

          curl -s "https://img.shields.io/badge/coverage-$COVERAGE%25-$COLOR" > coverage.svg

          mv coverage.svg ./.github/wiki/
          mv coverage.html ./.github/wiki/

      - name: Commit to Wiki
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: ./.github/wiki/
          skip_fetch: true
          skip_checkout: true
